info:
  contact: {}
paths:
  /transaction:
    post:
      consumes:
      - application/json
      description: takes array of bills in payment_bills body field and calculate
        transaction items
      parameters:
      - description: 'int array: allowed 2000 & 5000'
        in: body
        name: payment_bills
        required: true
        schema:
          items:
            type: integer
          type: array
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
        "400":
          description: invalid parameters
          schema:
            type: string
        "500":
          description: internal error
          schema:
            type: string
      summary: Create a New Transaction
swagger: "2.0"
